### ISSUE TITLE
Security Policy Tracking Issue

### ISSUE THREAD

**Issue by bmeck** [nodejs/security-wg#404]
[Proposal](https://docs.google.com/document/d/1h__FmXsEWRuNrzAV_l3Iw9i_z8fCXSokGfBiW8-nDNg/edit)

Current work is available at:
https://github.com/bmeck/node/tree/policy

Some docs for the current work:
https://github.com/bmeck/node/blob/policy/doc/api/policy.md

Slides explaining some modeling:
https://docs.google.com/presentation/d/153ME48cGiIo7RZpORjbbtogMbA4TeBZXv2EnEeKdZGg/edit#slide=id.g566f4eb51a_2_64

Status:

- code signing (punted to further milestone)

----

- SubResource Integrity
     - [ ] inclusion in policy manifest format
          - [x] self check
          - [ ] dependency check
     - [ ] check on loading code
          - [x] basic `require()` integration
          - [ ] loader integration
          - able to be moved off process (punted, needs help)

----

- freezing primordials (needs help)
     - polyfill loading mechanism (punted, needs help)
          - inclusion in cli
          - privilege requirements in policy manifest format
     - [ ] JS globals frozen ([adopt from proposal](https://github.com/Agoric/proposal-frozen-realms/blob/master/shim/src/deep-freeze.js))
     - [ ] Node.js core frozen

----

- constraining APIs (requires freezing primordials, needs help)
     - [ ] membranes around dependencies
     - [ ] userland defined constraints (punted)

----

- removal of Features - See https://github.com/nodejs/node/pull/22112

----

- tooling Integrations (punted, needs help)
     - generate/edit manifest when installing packages
     - verify integrities without loading node
     - mode to prompt on failed checks (requires escalated privileges)
          - integrity prompt
          - privilege prompt

It would be nice to have some meetings on how to coordinate work so that multiple different things can be worked on at the same time. Also, probably nice to make a fork within the foundation or under this working group.
